### ISSUE TITLE
Get All Feed Data At Once when Loading

### ISSUE THREAD

**Issue by aliguan** [aliguan/blueplanitv3#54]
get all feed data, don't make separate calls for each trip

**Comment by jinyu112** [comment]
promise all for solution

**Comment by jinyu112** [comment]
Frontend:
- feedComment.js line 130: why was user authentication removed?

Backend:
- comments.js line 64: remove updateCommentsAuthorAvatar endpoint

**Comment by aliguan** [comment]
Frontend: 
1. user authentication check happens in this.props.handlePostComment() function, in the parent component so it can trigger the alert 

backend:
1. done
