### ISSUE TITLE
Timestamp all data models

### ISSUE THREAD

**Issue by jinyu112** [aliguan/blueplanitv3#83]
also change timestamp to dateAdded

**Comment by aliguan** [comment]
Run these queries in prod mongo shell:
db.comments.updateMany( {}, { $rename: { "timestamp": "dateAdded"} })
db.trips.updateMany( {}, { $rename: { "timestamp": "dateAdded"} })
db.usersessions.updateMany( {}, { $rename: { "timestamp": "dateAdded"} })
